### ISSUE TITLE
TODO: update docs

### ISSUE THREAD

**Issue by stacksmash76** [autobrr/autobrr.com#44]
- [ ] add {{ .Size }} macro
- [ ] rtorrent as download client (along with limitation)
- [ ] mention necessity of binding to 0.0.0.0 for containers with a warning or somewhere more visible
- [ ] document pre-filter script with examples
- [ ] update puid/pgid vars for docker (?)
- [ ] more info on whatbox and similar scripts (?)
- [ ] make it more clear on what the user needs to do in order to get a certain site up and running. with pictures if possible.
- [ ] more warnings and huge red banners in order to avoid common mistakes (???)
- [ ] document categories for each/most popular trackers (?)
- [ ] document how to troubleshoot IRC issues (?)
- [ ] transfer pinned discord messages into docs (the ones that are missing that is?)
- [ ] discord notifications leak download client api keys (see message by supersonik in #suggestions on discord)
- [ ] `i just spent more time troubleshooting a filter prioritization issue than i'd like to admit. prowlarr and the arr's give the highest priority to the lowest number, so it took me a bit to figure out that the highest number has the highest priority with autobrr. may i suggest adding a sentence about that on the website under the filters -> basic section?` -- zippydude on discord

**Comment by Julianwan** [comment]
Hey guys i've been using autobrr and loving it

Just sharing some feedback based on working with the docs (and seeing the help wanted tag)

- Seeing supported categories by tracker is awesome, would love if you guys prompted users to make a community showcase of recipes
- In the "Advanced" portion of the app settings, the yellow warning banner makes it seem as if all the settings on the page are not advisable to touch, so freeleech feels really hidden as a toggle at the bottom
- As someone who accidentally got a 62gb classical compilation on a music tracker via autobrr, I really really like that you're thinking of giant red banners on some stuff, but have you considered some type of "bandwidth estimator" for when someone sets up a new filter?
- I've seen a huge improvement in adding trackers since I first installed, I actually went back and re-added a few of my first, but have you considered adding a stats page that overviews all the trackers? Similar to prowlarr? it can be as simple as "avg. releases per day by category" or "average size of torrents" or whatever
- Just fyi uhdbits does support freeleech filtering but isn't listed in your docs... could there be more?
