### ISSUE TITLE
TODO: gather download client info for commonly used seedbox providers (shared)

### ISSUE THREAD

**Issue by s0up4200** [autobrr/autobrr.com#68]
We're gathering information about how to set up Download Clients within autobrr from different shared seedbox providers since it often differs a lot.

The preferred setup for the docs is something that can be used with a remote instance of autobrr.

What's missing (Others are also welcome)

- [ ] swizzin.net qBittorrent
- [ ] swizzin.net Deluge
- [ ] swizzin.net rTorrent
- [ ] swizzin.net Transmission
- [ ] swizzin.net Sonarr
- [ ] swizzin.net Radarr
- [ ] swizzin.net Lidarr
- [ ] swizzin.net Readarr
- [ ] WhatBox qBittorrent
- [ ] WhatBox Deluge
- [ ] WhatBox rTorrent
- [ ] WhatBox Transmission
- [ ] WhatBox Sonarr
- [ ] WhatBox Radarr
- [ ] WhatBox Lidarr
- [ ] WhatBox Readarr

Here's what we have gathered so far:

- [x] Bytesized Deluge
- [x] Bytesized rTorrent
- [x] Bytesized Sonarr
- [x] Bytesized Radarr
- [x] Bytesized Lidarr
- [x] Bytesized Readarr
- [x] hostingby.design qBittorrent
- [x] hostingby.design Deluge
- [x] hostingby.design rTorrent
- [x] hostingby.design Sonarr
- [x] hostingby.design Radarr
- [x] hostingby.design Lidarr
- [x] Seedhost qBittorrent
- [x] Seedhost Deluge
- [x] Seedhost rTorrent
- [x] Seedhost Sonarr
- [x] Seedhost Radarr
- [x] Seedhost Lidarr
- [x] Seedhost Readarr
- [x] Seedhost Transmission
- [x] Feral qBittorrent
- [x] Feral Deluge
- [x] Feral rTorrent
- [x] Feral Transmission
- [x] Feral Sonarr
- [x] Feral Radarr
- [x] Feral Lidarr

~~- [ ] Feral Readarr~~ Not supported
~~- [ ] hostingby.design Readarr~~ Not supported
~~- [ ] hostingby.design Transmission~~ Not supported
~~- [ ] Bytesized Transmission~~ Not supported
~~- [ ] Bytesized qBittorrent~~ Not supported

Ref https://github.com/autobrr/autobrr.com/pull/61
